### ISSUE TITLE
sys/capability.h not found when compiling

### ISSUE THREAD

**Issue by w00kie** [hlandau/acme.t#1]
Running `make` I get the following error:

```
$ make
-e      [GO-GET]          github.com/hlandau/acme/cmd/acmetool
# gopkg.in/hlandau/service.v2/daemon/caps
src/gopkg.in/hlandau/service.v2/daemon/caps/caps-linuxc.go:9:28: fatal error: sys/capability.h: No such file or directory
 #include <sys/capability.h>
                            ^
compilation terminated.
make: *** [.gotten] Error 2
```

This is fix by installing `libcap-dev`:

```
sudo apt-get install libcap-dev
```

Just wanted to drop this here for anyone else hitting the same problem.

**Comment by hlandau** [comment]
Thanks for pointing this out, I've amended the README.

**Comment by dylan4224** [comment]
Thanks!

**Comment by Praying** [comment]
thanks

**Comment by erriapo** [comment]
I encountered this problem today. Thanks for the solution.

**Comment by Zakaria-Ben** [comment]
This is very useful. I faced a quite similar issue (i.e., capability.h) while compiling CRIU on a RASP. Thanks!

**Comment by sidstick** [comment]
Thank you!

**Comment by ghost** [comment]
Thanks you! Help me in getting the example code compiled for the book "The Linux Programming Interface". If anyone is here for this very purpose may I also point out [**this link**](https://man7.org/tlpi/code/faq.html#:~:text=%3A%20sys%2Facl.-,h%3A%20No%20such%20file%20or%20directory,not%20installed%20on%20your%20system.&text=On%20RPM%2Dbased%20systems%2C%20you,install%20the%20libacl%2Ddevel%20package.)
