### ISSUE TITLE
v.PublicKey.Curve.Params().Name undefined when compiling

### ISSUE THREAD

**Issue by canarduck** [hlandau/acme.t#5]
Running make I get the following error:

```
-e  [GO-GET]      github.com/hlandau/acme/cmd/acmetool
# github.com/hlandau/acme/acmeapi
src/github.com/hlandau/acme/acmeapi/api.go:232: v.PublicKey.Curve.Params().Name undefined (type *elliptic.CurveParams has no field or method Name)
Makefile:56: recipe for target '.gotten' failed
make: *** [.gotten] Error 2
```

This happens on a freshly cloned repository.
- Debian jessie 8.2
- armv7l

Thanks

**Comment by neoadventist** [comment]
I got the same thing @canarduck i'm upgrading go to 1.5 to see if there is a difference.

**Comment by neoadventist** [comment]
Yep it fixes it when you go to 1.5

**Comment by canarduck** [comment]
@neoadventist thanks ! 

It looks like the Name field was added between 1.4 and 1.5 https://github.com/golang/go/commit/081bc6b226f1df783f13657251cf4d4148179c25 

But for now I'm stuck with

```
$ go version
go version go1.3.3 linux/arm
```

I'm going to see if I can find a repository with a 1.5 golang version...

**Comment by hlandau** [comment]
You need Go 1.5 or later.

By the way, due to an unfortunate bug (12498) in Go 1.5.0 and 1.5.1, the HTTP-to-HTTPS redirector daemon won't work on Linux. Use 1.5.2 or HEAD if you need it.

**Comment by hlandau** [comment]
Binary releases are now available, which makes it easier to use acmetool on distros with old versions of Go.

https://github.com/hlandau/acme/releases

Closing this.
